In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
import numpy as np

In [7]:
X, y = load_diabetes(return_X_y=True)

In [3]:
X.shape

(442, 10)

In [8]:
X = X[:, 0][:, np.newaxis]

In [10]:
X.shape

(442, 1)

In [12]:
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [13]:
value_to_predict = np.array([0.04])[:, np.newaxis]

In [14]:
value_to_predict

array([[0.04]])

In [15]:
regressor.predict(value_to_predict)

array([164.30080714])

In [16]:
import pickle

In [17]:
with open('model.pkl', 'wb') as output:
    pickle.dump(regressor, output)

In [18]:
with open('model.pkl', 'rb') as input_file:
    regressor_from_file = pickle.load(input_file)

In [19]:
regressor_from_file

LinearRegression()

In [20]:
regressor_from_file.predict(value_to_predict)

array([164.30080714])